### ISSUE TITLE
A dot in repository name breaks `elm-make`

### ISSUE THREAD

**Issue by tomekwi** [elm-lang/elm-make#106]
Hey,

not exactly sure where to file this. It appears that if the `repository` field in the `elm-package.json` has a dot (other than that in the `.git` extension), the compiled JS code is broken. You end up with a dot in a variable name, which results in an `elm.js:7203 Uncaught SyntaxError: Unexpected token .`.

<details><summary>

**Steps to reproduce**</summary>

``` sh
git clone git@github.com:parametric-svg/parametric-svg.surge.sh
cd parametric-svg
git checkout 7d240b3
npm install; node_modules/.bin/elm-make source/Main.elm --output=public/elm.js
  # Or just `elm-make source/…` if you have elm-platform 0.17.1 installed globally
less +7203 public/elm.js
```

</details>

**Comment by evancz** [comment]
I am not sure there is a totally unambiguous way to handle dots, so the solution may be to disallow dots.

**Comment by michallepicki** [comment]
A dot in repository name is necessary when using [Github Pages](https://pages.github.com/).

**Comment by hachibu** [comment]
I know this is closed but since it's just machine generated code, how about hashing the user name and repository name? Then we could have dots in the user name or repository name.

```js
var _hachibu$hachibu.github.io$Main$renderJs = function (code) {}

var _72ce4c6f002d700abe7c44bb082d929bfddaf1bddb0efed9d27a175d71d880c1$Main$renderJs = function (code) {}
```

**Comment by elam03** [comment]
I just ran into this issue as well.

Changing the "repository" field was my solution, but it's not a great solution.
`"https://github.com/elam03/elam03.github.io.git"` -> `"https://github.com/elam03/elam03_github_io.git"`

**Disallowing dots is not a good solution for repos since they are supported and required by github.io pages (as michallepicki has mentioned).**

Hash the name or replace the dots with underscores in the generated code?

**Comment by tomekwi** [comment]
>  replace the dots with underscores

One of our goals here is to stay unambiguous. `https://github.com/elam03/elam03_github_io.git` is a valid repo name. Hashing seems like a great idea :)

**Comment by elam03** [comment]
`https://github.com/elam03/elam03_github_io.git` is a valid repo name, but that repo name does not satisfy the requirements to use Github's webpage hosting.

Github's web-hosting service is free and convenient, so repo names with dots are a common occurrence.

**Comment by chatterbeak** [comment]
I just hit this today, as a noob. Was completely stumped for hours, until I joined slack and asked someone. Spent about a day debugging my first project with a repo with a dot in it. It's been around for a while. Time to fix this -- and get rid of the "github" requirement. We use aws codecommit for "reasons.".

**Comment by evancz** [comment]
Dots in project names will be disallowed in an upcoming release

https://github.com/elm-lang/elm-compiler/blob/dev/src/Elm/Package.hs#L128-L129

**Comment by Mouvedia** [comment]
The issue wasn't about a missing explanation. Do we have a fix for the Github's web-hosting service case that was mentioned several times?

**Comment by evancz** [comment]
Open an issue with a http://sscce.org demonstrating your concern. When an issue gets long, it becomes about 10 different things, and not all can be addressed. New issues, specific description, good examples.

**Comment by Cypher1** [comment]
@evancz where is this on being fixed? Github pages repos still need dots and elm now doesn't allow dots or underscores so it is getting hard to work out how to resolve this.
Can we get elm to escape repo names (or hash them)?
Thanks

**Comment by zwilias** [comment]
For those who have doubts about this being fixed by explicitly disallowing it: the `repository` field only makes sense for libraries, not applications. I believe the field will be removed altogether for applications in 0.19. As such, this only means one cannot publish a package on package.elm-lang.org where the package-name contains a `.`.

So github pages repositories aren't really relevant to this discussion :)

**Comment by Cypher1** [comment]
If that's the case can we have elm make ignore it? It's really handy to be able to track github urls in the package so that devs can get the issue tracker url etc. from that (rather than relying on their own remote settings  which get distorted by forks etc).
It's okay if not but it would be handy.

Thanks
