### ISSUE TITLE
elm-make get stuck during compile

### ISSUE THREAD

**Issue by korczis** [elm-lang/elm-make#175]
I have problem with elm-make. It get stuck on Travis CI and in docker.

## Travis CI

- https://travis-ci.org/korczis/web-spa

## Docker

- Dockerfile - https://github.com/korczis/web-spa/blob/master/Dockerfile
- Webpack - https://github.com/korczis/web-spa/blob/master/webpack/webpack.config.js

I can provide more info if needed.

**Comment by andys8** [comment]
Hi @korczis, the [build is timing out](https://travis-ci.org/korczis/web-spa/jobs/255434705). Could you try to find out if the build blocks (forever) or if it is just very slow.

[`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) can be used to raise the timeout threshold. 

It could be the case that it's only very slow on CI (see: https://github.com/elm-lang/elm-compiler/issues/1473), but it doesn't have to be :)

**Comment by evancz** [comment]
I need an http://sscce.org to debug stuff like this. I suspect the info in https://github.com/elm-lang/elm-compiler/issues/1473 can help you out. For future reference, it will be way faster to ask for help through community forums like Slack or Discourse. Issues are used for bugs that have filtered through the community.
