### ISSUE TITLE
Output of "elm-make" fails to pass the Closure compiler

### ISSUE THREAD

**Issue by nikita-volkov** [elm-lang/elm-make#185]
Following is the error I get from Closure:

```
ERROR - Duplicate let / const / class / function declaration in the same scope is not allowed.
function badIndex(index, nestedProblems)
         ^^^^^^^^
```

The version is:

```
elm-make 0.18 (Elm Platform 0.18.0)
```

**Comment by evancz** [comment]
This particular thing seems to be caused by a mistake in the `Json.Decode` implementation that was fixed elsewhere, but I am reading this as a feature request for code gen to produce code compatible with Closure Compiler. I think doing that makes sense, but I do not want to track requests in issues.
