### ISSUE TITLE
Warnings are only reported when the module is compiled

### ISSUE THREAD

**Issue by ajhager** [elm-lang/elm-make#27]
This isn't actually a bug, but a feature. The problem is that a module that has only warnings will compile correctly and so never show warnings after the first elm-make. The Main module seems to always be recompiled, but others don't.

If it weren't "elm-make --warn" but "elm-make --lint" it would make sense perhaps to force all code outside of elm-stuff to recompile so that warnings are always reported.

**Comment by tcoopman** [comment]
I've just found this out too, so just some info if someone else runs into this
I was running `elm-reactor`and I didn't get any warnings about unused imports when I compiled with `elm-make --warn`. Probably because `elm-reactor` had compiled the module already.

When I stopped elm-reactor and made a change to a file, then I got warnings.

**Comment by evancz** [comment]
Tracking from meta issue #98
