### ISSUE TITLE
Is it possible to specify output directory and default build command ? 

### ISSUE THREAD

**Issue by phtrivier** [elm-lang/elm-make#36]
I'm currently running a build with a command like this: 

~~~
elm-make elm/thm.elm --output public/javascripts/thm.js
~~~

My elm-package.json specifies a "source-directories" folder ; is there an option to make it push compiled js files directly to "public/javascripts", by default ? 

Also, is there an option to make a build "default" ? When running `elm-make` without arguments, it returns a message `Success! Compiled 0 modules.` ; what is such a command supposed to do ? 

(I'm sorry if this is all in the docs somewhere, I could not find a reference for the elm-package.json file.)

**Comment by evancz** [comment]
Sorry for the delay. It is not possible to do what you are saying right now.

As for what happens when you run `elm-make` with no arguments, it is trying to build all of the `exposed-modules`. It kind of assumes you are making a package, not a product. There are plans to make this nicer in the next release. @laszlopandy has opened some issues describing this on this repo.
