### ISSUE TITLE
elm make autocomplete

### ISSUE THREAD

**Issue by cacplate** [elm-lang/elm-make#62]
When using `elm make` without the hyphen, tab does not complete filenames but it does when using `elm-make`. Is there a difference between the two commands that would explain this behaviour? Anyway, it's not really problematic but it is easier to type ` ` than `-`.

**Comment by rgrempel** [comment]
It sounds like you're talking about auto-completion when typing shell commands in a terminal. Elm isn't really doing anything at that stage -- the behaviour of auto-completion is controlled by whatever shell you're using (i.e. bash, tcsh, csh, etc).

Now, one difference between `elm-make` and `elm make` is that in the second case, `make` is the first parameter (rather than part of the command name). So, perhaps there is something in your shell's autocompletion logic that turns on whether the first parameter is itself a file name or something like that.

Though, I just tried it in `bash` on Mac OS X, and it doesn't make a difference there.

**Comment by cacplate** [comment]
I indeed tried it with bash and it works as expected. It is the zsh behaviour that is problematic so no problem on your side. closing.
