### ISSUE TITLE
Separate elm runtime library from app module

### ISSUE THREAD

**Issue by itrelease** [elm-lang/elm-make#64]
Currently if you make build of your elm app it goes in one bundle that contains elm runtime and also user module. But for production usage it would be better to keep them separate so runtime library can be cached by browser and if you make changes in your app users only have to download this app module. @rtfeldman what do you think?

**Comment by rtfeldman** [comment]
The tradeoffs on this are tricky. A future release of Elm is planned have dead code elimination, meaning portions of libraries you aren't using won't be part of the compiled output. In that world, you might be choosing between an initial download that's several times as large in order to be cache-friendly in the long term.

ClojureScript has had dead code elimination via the Google Closure Compiler for awhile, and it looks like this proposal hasn't had much traction in the past few years: https://github.com/lynaghk/clojurescript-compiler-proposal/issues/4

Given that, it wouldn't surprise me if the savings from caching don't turn out to outweigh the loss of dead code elimination in practice. Could be different for Elm, of course, but my default assumption would be that this would turn out to be a false economy except in very particular use cases.

**Comment by rgrempel** [comment]
Although, if we're talking about `Runtime.js` in particular, I wonder how that particular file will be handled under dead-code-elimination. That is, I suppose it's possible that that file will benefit from dead code elimination, but it's also possible that it might not -- it's not 'normal' native code, so it may be a third case for DCE. (Where the first case is the *.elm files and the second case is the normal native code files).

**Comment by evancz** [comment]
Known concern, will revisit when possible.

**Comment by Voronchuk** [comment]
Personally, I prefer to make elm-integration as the pack of independent modules instead one huge single page application, at max it's 3 standalone generated JS files on a single page: `chat`, `tools` and `workarea`. Is there is a way to optimise the output size without making a single messy application?

**Comment by inoas** [comment]
Any news on this? 2y closed?

I am looking to adapt elm instead of jQuery for mostly content-driven websites intermangled with sone apps/widgets such as chats, product configuration wizards, basket and complex checkout multi step forms etc.

However 95% is still content and I am looking for elm as a drop in such as jquery and vue-js do it.

Now I don’t want to duplicate the shared elm lib on successive requests.

What I am looking for is first request ~> dead code eliminated elm runtime+app - then http2 prefetch of the lib for consequtive requests and stand alone app code.

I know for SPAs elm is a great choice but the dominance of wordpress on the web tells a story if mostly static (e.g. non interactive, non-app) content driven web.

Any chance?

**Comment by tskalczynski** [comment]
Hello,

   And how about that one?

   Is that kind of separation of the Elm runtime (big one, but always the same, on each page, thus cached) and page program code (using the Elm runtime) possible now (May 2018)?

Thank you!
Regards,

Tom
