### ISSUE TITLE
elm-make 0.16 creates index.html by default

### ISSUE THREAD

**Issue by savuori** [elm-lang/elm-make#68]
Using a command  `elm-make Module.elm` used to create only elm.js -file, now it creates an index.html file. If this is intentional it might be worth a mention in the upgrade guide because it causes tools like emacs' compile buffer have new side-effects, like overwriting the index.html.

**Comment by doppioslash** [comment]
also, how do we compile a stand-alone js file now? `--output=file.js` doesn't work.

**Comment by igrep** [comment]
Well, I experienced both cases in 0.16.
According to my experience, it creates `elm.js` in newly created elm project,
but it creates `index.html` in some existing projects.
It might be caused when `index.html` is already created.

**Comment by twitchard** [comment]
This behavior should be removed. It clobbered my existing index.html and made me lose work. Very off-putting to newbies like me.

**Comment by evancz** [comment]
This change was made to accommodate new folks. If someone new to Elm is using `elm-make` they probably just want the HTML to be set up for them. If they decide the want ports, they will have found docs that explain how to do that with an `--output` flag.

That is the rationale. I get that there are tradeoffs, but this seems like "the best compromise" for now. Perhaps it makes sense to call it something besides `index.html` but also kind of doesn't make sense.

**Comment by twitchard** [comment]
@evancz 
I propose the following: suppose elm-make includes an HTML comment somewhere in its output, indicating the file was generated with elm-make. Then, when elm-make detects that it is about to overwrite a file, it checks for that comment. If the comment is present, it overwrites the file without another thought. Otherwise, it warns the user it is going to overwrite a file and prompts.
