### ISSUE TITLE
Requirements for "repository" field in elm-package.json too strict

### ISSUE THREAD

**Issue by tdammers** [elm-lang/elm-make#71]
The "repository" field in elm-package.json now seems to be mandatory and subject to some enforced validation rules. I have run into the following issues:

- Not every project is a standalone package; I'm using Elm to build parts of my frontend as part of a larger project, and the Elm code lives in the main repository next to the other parts. This isn't a crazy setup, but having a "repository" entry in elm-package.json at all seems wrong, except maybe for informational purposes.
- Git is not the only SCM, but the repository URL is required to end in `.git`.
- Github is not the only git hosting service, but the repository must have `github.com` as its domain name.
- The repository may not be public, so an ssh-based URL rather than https makes sense, but that's not allowed either.
- Uppercase letters are forbidden, even for parts of the URL where existing standards explicitly allow them.

I can understand the rationale, but I believe that these checks are overly strict even for a package intended for publication (but even there, they shouldn't prevent a build, only the publish); for the kind of code I'm writing right now, they are absolute show stoppers, so I'd love to see a way to just disable them.

**Comment by jvoigtlaender** [comment]
Probably relevant for you: https://github.com/elm-lang/elm-make/issues/59

**Comment by tdammers** [comment]
Ah, yes. I'll join the discussion there.

**Comment by tdammers** [comment]
No, that doesn't help at all. Removing the exposed-modules field and adding a main-modules one still causes elm-make to demand a repository in the "correct" format.

**Comment by jvoigtlaender** [comment]
I'm not certain what you mean by
> Removing the exposed-modules field and adding a main-modules one still causes elm-make to demand a repository in the "correct" format.

As far as I know, the proposal from that other issue is not implemented yet. So whatever elm-make is doing right now is not an indication of what it would be like if that proposal would be implemented. And the proposal explicitly says that if there is no exposed-modules field, then there would be no repository field. So I don't see how what you say can make sense, that elm-make would still demand that the (non-existent!) repository field would be in a specific format.

**Comment by tdammers** [comment]
So how do I get elm-make to not demand a "repository"?

**Comment by jvoigtlaender** [comment]
Currently you can't. And I don't think anyone claimed you can. What I linked to was an issue with discussion, not a pull request with finished implementation.

**Comment by tdammers** [comment]
Yes, I understand that. It just didn't occur to me that people would actually invent a system that requires a github URL in order to just build a project, so I (wrongly) assumed that there would be a way to turn it off. Especially since the previous version didn't reject my project file.

**Comment by jvoigtlaender** [comment]
Well, that the previous version didn't rejept your project file is likely due to the case that this requirement:
> Uppercase letters are forbidden, even for parts of the URL where existing standards explicitly allow them.

was newly introduced with elm 0.16.

**Comment by mathw** [comment]
Can the requirement just be dropped entirely? If I'm working on something commercially that's hosted on internal git servers I don't want to be inventing spurious GitHub URLs just to satisfy the build system. Not everything is open source, and not even all of that is hosted on GitHub.

**Comment by ethagnawl** [comment]
At the risk of contributing noise, I'd like to +1 @tdammers and @mathw's requests for the repository requirement to be removed.

Unless I'm overlooking something (which is very possible), I see no no good reason why a malformed or missing (_GitHub_) repository value in an elm-package.json should prevent someone from experimenting locally or working through a tutorial - like it just did to me.

**Comment by shmish111** [comment]
Is there any news on this? I was about to start playing with elm but I am also trying to stop using github. It seems beyond comprehension that I wouldn't be able to use elm without a github repo?

**Comment by tdammers** [comment]
On Tue, Apr 05, 2016 at 07:06:01AM -0700, David Smith wrote:
> Is there any news on this? I was about to start playing with elm but I am also trying to stop using github. It seems beyond comprehension that I wouldn't be able to use elm without a github repo?
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/elm-lang/elm-make/issues/71#issuecomment-205823897

For a local package, you don't actually need a github repository, you
just have to give it a well-formed github URL.

-- 
Tobias Dammers - tdammers@gmail.com

**Comment by shmish111** [comment]
OK cool, but this has put a serious damper on things for me. It's one thing to provide nice integrations for github but to enforce using or at least pretending to use it is below the belt IMO. This needs to be fixed before I could recommend elm to anyone.

**Comment by evancz** [comment]
I understand the problem here. Part of creating a successful project is doing the minimal viable thing. It may not work for everyone at first, but you have to have something to grow from. I think we will make things more flexible in time, but I do not have a fixed timeline for these things.

I do not think this issue will help track the core concern here. Obviously things like this are important and will come in a revamp of how stuff works. Thanks for reporting!

**Comment by pshendry** [comment]
Mark me down as another Elm novice who got hung up on this for 15 minutes (and who now has to awkwardly put a made-up GitHub URL in his elm-package.json). @evancz maybe an open issue doesn't help you personally, but certainly it's helpful for those interested in changing this functionality? Seems like an ideal "easy but helpful" type of issue for a new contributor to get started with.

**Comment by kspeakman** [comment]
Just ran into this myself on a local-only git repo. Kindof annoying. I ended up using https://github.com/local/local.git

**Comment by stevenleeg** [comment]
Any news on this? I've also been spending time with this issue and think it's ridiculous that I'd be required to use github for projects by a language's build system.

**Comment by ThomasLocke** [comment]
As a beginner I completely stumbled on this one also. Lots of time wasted.

Not being able to use a private repo URL is a bit annoying. Also the github requirement seems completely out of whack. Lots of other options out there.

**Comment by pshendry** [comment]
FWIW, this issue and its handling drove me to seek out and eventually settle on PureScript and purescript-halogen for my project instead of Elm.

**Comment by omouse** [comment]
My only complaint is that gitlab urls don't seem to work. I'm an advocate for free/open source and don't mind if everything in the world was open source so getting Elm users to publish more things as open source is a win in my opinion.

Keep up the awesome work but uh, let me use gitlab please :wink:

**Comment by tryge** [comment]
I just ran into this issue and I'm quite disappointed, because to me it doesn't make any sense at all. I also put a fake github url in there - is this really improving the situation?

@evancz I understand your argument to do the minimal viable thing, however, in my opinion this restriction is not viable at all. For me the minimal viable thing is to check while publishing and that probably on the server side, so you can change validation rules without having to update the toolchain on each client.

**Comment by Mouvedia** [comment]
> …this kind of stuff is on my personal list anyway.

@evancz you should post that list as a GFM task list in a new issue or reopen this one.

**Comment by tryge** [comment]
I actually read @evancz's comment, but it didn't help my situation as just closing an issue without resolution is not very comforting - especially after having spent an hour because I didn't believe it at first (probably my fault as the first time I came across this issue I didn't read the whole issue and only saw that it is closed, therefore I assumed that it is fixed...)

I should have waited for an hour to calm my emotions before posting above comment, I think it was way too harsh, instead I should have written something like the following:

If it is too much effort to actually fix the issue in the near future, what would have actually helped me is the compiler giving me an explicit hint. Consider: 

> It is true that only github urls are allowed. This is in fact a restriction that is too narrow, but it is one that will be lifted in the future. If you host your code on a different platform please use `https://github.com/invalid/repo.git` in the meantime. You can follow the discussion on https://github.com/elm-lang/elm-make/issues/71

With this hint, especially beginners (like me) won't lose time. Personally, I'd add some reasoning for the existing behaviour and an insight that this might have been a wrong decision at the time (no matter if you actually think that this is true, but this addition will soften the emotional distress when encountering such an issue within the first 5 minutes)

**Comment by omouse** [comment]
@tryge that makes sense, it's a good placeholder for now until someone submits a patch to support other URLs.

**Comment by jvoigtlaender** [comment]
@omouse, I don't think you have understood how things go here. It is not, at all, an issue of "until someone submits a patch to support other URLs". Such a patch could be submitted today, and it wouldn't change a thing about the status here. The feature in question wouldn't be any bit closer to becoming available in an Elm release. Not *any bit*.

**Comment by JoeyEremondi** [comment]
Perhaps the solution for now is to remove the repository field, and replace
it with GHUsername and GHRepo fields, so that users can't inadvertently put
a non-GH repo there, and those not using github will see immediately that
dummy values should be there?

On Fri, Dec 30, 2016 at 2:32 PM, Janis Voigtländer <notifications@github.com

**Comment by tryge** [comment]
@JoeyEremondi I'm not sure this would actually help. The problem for me was not that I didn't recognise the compiler error `The given domain does not start with <https://github.com/>`, the problem was that **I didn't believe it** and therefore wasting time to find workarounds to use my actual repository, and after discovering this issue an explanation why it was designed like it is.

@jvoigtlaender I didn't find any information on how things go for elm releases. I think this issue is impairing the conversion rate, and if this is not intentional, what can I do to bring in the changes for the hint I suggested (or a variation, or a different solution)? Where are these kind of changes discussed if not here on github?

**Comment by jvoigtlaender** [comment]
About why GitHub is not the place where such changes are discussed/decided, look at process-bot's messages like this: https://github.com/elm-lang/elm-make/issues/145#issuecomment-269718745 (the only reason there isn't one like it above here is that this issue here is older than the introduction of process-bot).

About why having a patch with the changes here wouldn't make any difference about when the desired feature makes it into an Elm release: Watch the talk "Code is the Easy Part" by Evan Czaplicki on YouTube.

**Comment by tryge** [comment]
@jvoigtlaender Thank you for the hints. I'm not a native speaker of English, so I might have used a phrase that didn't express what I was actually interested in. Specifically I'd like to know _where_ the discussion for this (and related) issues take place so I can join the discussion, or at least follow it.

I have already watched the talk you referred to (and others), before I tried to do anything with elm. Some of these talks go about their focus in making it easy for beginners to start with, this issue is in direct conflict with this goal. I'd like to help, if you don't want it, I'm a little sad for a while but ultimately I'll focus on other things :-)

**Comment by Mouvedia** [comment]
OK let's slice this issue in smaller tasks:

- [ ] optional repository property
- [ ] allowing uppercase letters
- [x] support for Github
- [ ] support for Bitbucket
- [ ] support for Gitlab
- [ ] support for other schemes (e.g. SSH)

@evancz which task would you willing to tackle in 0.19?  
Id say that fixing the first two shouldn't be that hard.

**Comment by jvoigtlaender** [comment]
@tryge, your question about *where* those discussions take place is explicitly answered by the `process-bot` messages I pointed you to, namely when it says (actually several times) that in the Elm community GitHub is not really used for discussions, instead "the community forums" (http://elm-lang.org/community) are.

The talk I pointed you to is explicitly explaining how things develop for Elm releases. Maybe you want to watch it again, because you saying that you didn't find any information on how things go for Elm releases is strange in that context.

Finally, it is not at all about whether *I* (assuming the "you" in your comment is addressed at me) want your help. I was only pointing out where you can find information about "the rules" of how the Elm community is operating in terms of contributions to the language and main tools repositories. I don't make, nor made, those rules. I don't even necessarily agree with them. Don't blame the messenger. :smile:

**Comment by tryge** [comment]
@jvoigtlaender Thank you for pointing me to the information. In both cases the information is too vage for me to know how to proceed, I'm probably damaged from corporate guidelines etc. I accept that this is the information available and will wait and observe.

I did not mean you in person, but addressing the whole project. I don't blame anyone, I'm sorry if it comes across this way. I'm curious and I'm a little (or more) neurotic so if there's wiggle room than I'm uncomfortable, therefore I ask a lot of questions and try to clarify them.

One thing though, as issues represent a work queue (as communicated in the bot message) it's a good sign to reopen one of the issues or creating a new one. In the current state it seems there's no work to be done.

**Comment by jvoigtlaender** [comment]
To the last aspect, I can only say that Evan repeatedly states in various issues (often upon closing them) that he as a privately held work queue, and that he knows certain things remain to be done, and that he sees no benefit in having a GitHub issue open about them (because that won't make him work on a given issue any sooner).

And yes, people ever again ask whether he can make that "internal" work list public, basically for the same reason that you would be more comfortable with seeing an open issue on the feature under discussion here. 

But we are where we are.

**Comment by tdammers** [comment]
> Evan repeatedly states in various issues (often upon closing them) that he as a privately held work queue, and that he knows certain things remain to be done, and that he sees no benefit in having a GitHub issue open about them (because that won't make him work on a given issue any sooner).

This, IMO, is a much more harmful issue that the one at hand, and reassures me that my intuition to drop Elm and start using other platforms for my projects was right.

**Comment by pshendry** [comment]
I'm inclined to agree... Opening a ticket for an unreported bug/feature ought to be a welcome contribution to an OSS project, and it's super discouraging to potential new code contributors to see their first participation tossed aside in the name of a private roadmap they had know way to know about. It's the antithesis of an OSS project IMO.

That said, I don't think the maintainers are going to change their policies based on some requests in a closed issue, so there's probably not much value in discussing it to death.

**Comment by robvandenbogaard** [comment]
The value in keeping a discussion here is that people will still end up at this issue from search engines, because they just don't understand why the requirements for the repository field are so strict, even when they see (and even appreciate) the case for requiring *packages* to have a github repo. Personally I don't understand why *non-package elm projects* (apps) need to have a github repo. Often I like to first try out things privately and publish later.

**Comment by pietro909** [comment]
It really feels awkward committing an `elm-package.json` to our internal Bitbucket repo with a fake URL just because the package manager accepts only Github.

I can understand that the development is slow and quite closed, but please try to imagine explaining this to a CTO, telling that an apparently trivial issue from 2015 is still open.

**Comment by yowzadave** [comment]
I also was confused by this issue when attempting to experiment with elm—add me to the list of new users who have spent time looking for solutions to this while trying to do basic experiments. Seems strange that it's been an open issue for nearly two years?

**Comment by purohit** [comment]
Just ran into this trying out Elm for the first time. To me it is a nonsensical requirement in an otherwise well-thought-out ecosystem. It confused me.

**Comment by zwilias** [comment]
Hi @purohit. Please note that the repository field is not relevant for applications (only for libraries) and the recommendation the default user/project as it is. As far as I'm aware, the plan is to remove this field for applications altogether in the upcoming 0.19 release.

I hope that answers the implicit "should I even touch that field" question, and may also result in less confusion once 0.19 is released :)

**Comment by purohit** [comment]
Thanks, that does answer the question. I was concerned it was going to attempt to publish something I wanted to remain private.

**Comment by Mouvedia** [comment]
@evancz are there more checkboxes that should be ticked in [that list](https://github.com/elm-lang/elm-make/issues/71#issuecomment-269856611)?
