### ISSUE TITLE
add option/switch for "color markers" in json output

### ISSUE THREAD

**Issue by rundis** [elm-lang/elm-make#73]
I'm using the json reporter for outputting errors/warnings in the linter feature of [elm-light](https://github.com/rundis/elm-light). That works out great, however I loose one really awesome feature from the console output... coloring of the details of each error/warning. 

It would be awesome if there was a flag that allowed for some sort of (color) marking. I can live with getting the ansi-color codes if that's the simplest to implement (or ```<marker> ... </marker>```).

**Comment by glenjamin** [comment]
I had a little look into what it would take to get this working, it turns out to be annoyingly tricky for a few reasons.

I was trying to add a `--color` flag which forced colour output, however the colouring code is in `elm-compiler` (for error messages) and `elm-make` for the banners and layout.

However, it looks like it would be possible to force colour onto the error messages - they get produced with colour, and then it's stripped out before being passed back to `elm-make` for display. This would mean a change to the compiler's interface to provide a way to tell it to retain colour in string/json output, and then passing that along from make.

Another thing which tripped me up is that `System.Console.ANSI` appears to do console detection itself, so if you attempt to `hSetSGR` on a normal pipe, nothing happens.


Hopefully that's useful if anyone else comes to have a go at this. I might have another shot later.


> On another note: this is some of the most accessible Haskell code I've come across - I was able to follow it and make changes pretty easily - great job Evan & co!

**Comment by evancz** [comment]
Tracking from meta issue #98
