### ISSUE TITLE
`var` is being used in an unexpected way - obscure error

### ISSUE THREAD

**Issue by pzavolinsky** [elm-lang/elm-make#76]
`elm-make 0.16 (Elm Platform 0.16.0)`

In mid-refactor I was removing unused values from my functions and I forgot to remove an `Int` arg from one of them (`updateB`):

Here's the full repro:

```elm
type alias Model =
  { a: Float
  , b: Int
  }

update : Model -> Model
update model =
  let
    newA = updateA model.a -- (A) `model` is being used in an unexpected way.
    newB = updateB model -- (B)
  in
    { model
    | a = newA
    , b = newB
    }

updateA : Float -> Float
updateA = identity

updateB : Int -> Model -> Int
updateB _ _ = 1

```

The error message shown in (A) is:
```
`model` is being used in an unexpected way.

11│     newA = updateA model.a
                       ^^^^^
Based on its definition, `model` has this type:

    Int

But you are trying to use it as:

    { b | a : a }
```

This is confusing because the type annotation for `update` clearly states that `model` is of type `Model`:

```elm
update : Model -> Model
```

The actual problem is that in (B) we are trying to partially apply `updateB` to a `Model` instead of an `Int`.

**Comment by jvoigtlaender** [comment]
I'm afraid you have reported this to the wrong repository. More appropriate would be https://github.com/elm-lang/error-message-catalog. In fact, I guess what you encountered here is already covered by at least one issue there: https://github.com/elm-lang/error-message-catalog/issues/71.

In any case, please close the issue here, possibly (if not covered by the above) re-opening it at the other repository.

**Comment by pzavolinsky** [comment]
Ok, cool, will review the issue in the other repo to avoid creating a dup.

Cheers.
