### ISSUE TITLE
more control over builds

### ISSUE THREAD

**Issue by geekyme** [elm-lang/elm-make#92]
For a single page application, its necessary to control build size. I'm a Webpack / React-ian and so I can control webpack to dynamically load chunks as needed. Eg. When I move from page A to page B, I load B's assets.

I noticed that this control isn't available on Elm and could be a big barrier against serious adopters who want to build production ready applications. 

Would be cool to expose all the functionality that Webpack has on Elm / Elm-make

Good work on the Elm so far anyway, I'm taking it quite seriously :+1:

**Comment by evancz** [comment]
This is something we want to do long-term, but I don't think we'll be able to "just add it" as things stand.

I expect this will be added as things mature more and the companies using Elm start needing stuff like this more urgently. I'm going to close because I'm tracking this in my own personal plans.
