### ISSUE TITLE
elm-make writes to HOME

### ISSUE THREAD

**Issue by sjmackenzie** [elm-lang/elm-make#93]
So when using `elm-make` on nixos I get an error: `elm-make: /homeless-shelter: createDirectory: permission denied (Permission denied)`

This means `elm-make` is writing to `$HOME` and `nix` specifically doesn't allow this so it makes the problem obvious by throwing a `homeless-shelter` error.

Is there a way to override `elm-make` to not use $HOME variable?

**Comment by jvoigtlaender** [comment]
Actually, it's `elm-package` (and also `elm-repl`) that writes to `$HOME`. You only experience it with `elm-make`, because `elm-make` invokes `elm-package` (as a library, not the `elm-package` executable). So your concern should be an issue over in the other repository.

The answer to your question is that no, currently there is no way to override this behavior. What it would take is to make it so that [this line](https://github.com/elm-lang/elm-package/blob/5f5a7b8215f6fc13b079876effca14c4b33a76ad/src/Manager.hs#L32) doesn't get its root from `System.Directory.getAppUserDataDirectory`.

**Comment by sjmackenzie** [comment]
Okay, thanks so much for your help!

**Comment by jvoigtlaender** [comment]
I'm not familiar with Nix, but would it maybe help the situation if Elm would be using [`System.Directory.getXdgDirectory`](https://hackage.haskell.org/package/directory-1.2.5.1/docs/System-Directory.html#v:getXdgDirectory) instead of [`System.Directory.getAppUserDataDirectory`](https://hackage.haskell.org/package/directory-1.2.5.1/docs/System-Directory.html#v:getAppUserDataDirectory)?

**Comment by sjmackenzie** [comment]
This would be perfect.

**Comment by sjmackenzie** [comment]
Ideally, exposing an `--arg` allows one to override the path. Many build tools allow for this.

**Comment by jvoigtlaender** [comment]
Okay, then I think the course of action is clear: Open issues with these suggestions in the `elm-package` and `elm-repl` repositories.

**Comment by sjmackenzie** [comment]
will do!

**Comment by sjmackenzie** [comment]
So I had a look at `getXdgDirectory`
```
XdgCache resolves to ~/.cache
XdgConfig resolves to ~/.config
XdgData resolves to ~/.local/share
```
as per https://hackage.haskell.org/package/directory-1.2.5.1/docs/System-Directory.html#t:XdgDirectory

All of the above will fail on `nix`, so by far the best solution would be to override the `$HOME` so that it recreates everything inside a `target` directory. This is very similar to the way `rustc` creates a `target` folder.
